# build
FROM golang:1.22.8-alpine AS builder

RUN apk add --no-cache \
    clang \
    curl \
    git \
    wget \
    vim \
    gcc \
    make \
    musl musl-dev \
    ncurses ncurses-dev ncurses-libs ncurses-static \
    openjdk11

ENV PATH=${PATH}:/usr/local/go/bin

WORKDIR  /opt/workspace/yc-agent

ENTRYPOINT ["/bin/sh"]
