# build
FROM golang:1.21.1-alpine AS builder

RUN apk update \
 && apk add \
    curl \
    git \
    wget \
    vim \
    gcc \
    make \
    musl musl-dev \
    ncurses ncurses-dev ncurses-libs ncurses-static \
    openjdk11

ENV PATH=${PATH}:/usr/local/go/bin

WORKDIR  /opt/workspace/yc-agent-repo

ENTRYPOINT ["/bin/sh"]
